spring:
  application:
    name: dynamic-schedule-service
  profiles:
    active: local
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      username: nacos
      password: nacos
  config:
    import:
      - optional:nacos:dynamic-schedule.yml
